### ISSUE TITLE
C++11 support in older GNU compilers

### ISSUE THREAD

**Issue by yegorich** [entropia/libsocket-can-java#3]
According to http://gcc.gnu.org/projects/cxx0x.html compilers before 4.7 use another parameter to activate C++11 features: -std=c++0x and -std=gnu++0x.

What about trying autotools or cmake to automatically determine compiler features, library paths?

**Comment by hannes-zz** [comment]
Sorry for taking so long to reply. I'll have a look what I can do about it at the weekend.

**Comment by hannes-zz** [comment]
We don't need gnu++0x anymore.
